services:
  app:
    image: apis_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
