services:
  app:
    image: apis_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres.istboiezkirncgtaxfvp:orIRMWqKJcjqQBmz@aws-0-sa-east-1.pooler.supabase.com:5432/postgres"
      DATABASE_HOST: "aws-0-sa-east-1.pooler.supabase.com"
      DATABASE_USER: "postgres.istboiezkirncgtaxfvp"
      DATABASE_PASS: "orIRMWqKJcjqQBmz"
      DATABASE_LINK: "https://istboiezkirncgtaxfvp.supabase.co"
      DATABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdGJvaWV6a2lybmNndGF4ZnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTc5OTI3MzUsImV4cCI6MjAzMzU2ODczNX0.CbKi8mvh1D4gbIyJiXU2Krf-1a_xDOEZJAe3QVFD2bw"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      EMAIL_USER: "afiovinicius@gmail.com"
      EMAIL_PASS: "fpqb lmjj onjx ivak"
      REDIS_URL: "redis://localhost:6379/0"
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres.istboiezkirncgtaxfvp
      POSTGRES_PASSWORD: orIRMWqKJcjqQBmz
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
